In [91]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [92]:
df = pd.read_csv("simonov.csv")
df

,Unnamed: 0,Rank,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,0,14710,319,2011.0,1,11,0.000000,0.000000,0.707107,0.000000,0.707107
1,1,2738,83,2010.0,3,9,0.516640,0.208854,0.000000,0.098931,0.824425
2,2,13538,158,2011.0,4,29,0.707107,0.000000,0.000000,0.000000,0.707107
3,3,13800,256,2009.0,8,32,0.600000,0.000000,0.000000,0.000000,0.800000
4,4,8062,521,2009.0,0,9,0.571187,0.000000,0.000000,0.219687,0.790875
...,...,...,...,...,...,...,...,...,...,...,...
548,548,3239,499,1995.0,8,100,0.000000,0.000000,0.707107,0.000000,0.707107
549,549,9265,369,2009.0,8,21,0.613006,0.111456,0.000000,0.055728,0.780189
550,550,8530,40,2015.0,0,116,0.383023,0.218870,0.164153,0.109435,0.875481
551,551,4962,432,1994.0,10,87,0.000000,0.000000,0.707107,0.000000,0.707107
552,552,1794,335,1990.0,9,89,0.345669,0.127747,0.360698,0.015029,0.856659

In [93]:
df.loc[df["Other_Sales"] > 0.07, "Other_Sales"] = 1

In [94]:
df.loc[df["Other_Sales"] < 0.07, "Other_Sales"] = 0

In [95]:
df.Other_Sales = df.Other_Sales.astype(int)

In [96]:
df

,Unnamed: 0,Rank,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,0,14710,319,2011.0,1,11,0.000000,0.000000,0.707107,0,0.707107
1,1,2738,83,2010.0,3,9,0.516640,0.208854,0.000000,1,0.824425
2,2,13538,158,2011.0,4,29,0.707107,0.000000,0.000000,0,0.707107
3,3,13800,256,2009.0,8,32,0.600000,0.000000,0.000000,0,0.800000
4,4,8062,521,2009.0,0,9,0.571187,0.000000,0.000000,1,0.790875
...,...,...,...,...,...,...,...,...,...,...,...
548,548,3239,499,1995.0,8,100,0.000000,0.000000,0.707107,0,0.707107
549,549,9265,369,2009.0,8,21,0.613006,0.111456,0.000000,0,0.780189
550,550,8530,40,2015.0,0,116,0.383023,0.218870,0.164153,1,0.875481
551,551,4962,432,1994.0,10,87,0.000000,0.000000,0.707107,0,0.707107
552,552,1794,335,1990.0,9,89,0.345669,0.127747,0.360698,0,0.856659

In [97]:
from sklearn.model_selection import train_test_split
Y = df["Genre"] #Ð¿Ñ€Ð°Ð²Ð¸Ð»ÑŒÐ½Ð¾
X = df.drop(columns=["Genre"]) #Ð¿Ñ€ÐµÐ´ÑƒÐ³Ð°Ð´Ð°Ð½Ð¾
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [98]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [99]:
dtc = DecisionTreeClassifier()
dtc = dtc.fit(x_train,y_train)
dtc_plot = DecisionTreeClassifier()
dtc_plot = dtc_plot.fit(x_train.iloc[::1],y_train.iloc[::1])

ValueError: Input X contains NaN.
DecisionTreeClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
plt.figure(figsize=(8,8))
tree.plot_tree(dtc_plot,filled=tree,fontsize=6)

In [ ]:
y_predict = dtc.predict(x_test)
con_mat = metrics.confusion_matrix(y_test,y_predict)
con_mat

In [ ]:
sns.heatmap(con_mat,annot=True,fmt="d")
plt.xlabel('pred')
plt.ylabel('real')

In [ ]:
print('accuracy_score',metrics.accuracy_score(y_test,y_predict))
print('recall_score',metrics.recall_score(y_test,y_predict))

In [ ]:
print('precision_score',metrics.precision_score(y_test,y_predict))

In [ ]:
print('f1_score',metrics.f1_score(y_test,y_predict))

In [ ]:
dtc_plot = DecisionTreeClassifier(max_depth=2,min_samples_leaf=2,max_leaf_nodes=5)
dtc_plot = dtc_plot.fit(x_train.iloc[::1],y_train.iloc[::1])

In [ ]:
plt.figure(figsize=(7,7))
tree.plot_tree(dtc_plot,filled=tree,fontsize=6)

In [ ]:
print('accuracy_score',metrics.accuracy_score(y_test,y_predict))
print('recall_score',metrics.recall_score(y_test,y_predict))
print('precision_score',metrics.precision_score(y_test,y_predict))
print('f1_score',metrics.f1_score(y_test,y_predict))
print('confusion_matrix',metrics.confusion_matrix(y_test,y_predict))